#!/bin/sh

# This should install all the dependencies of Minecraft Client

sudo pkg install alsa-lib brotli dejavu expat fontconfig freetype2 giflib java-zoneinfo-2021.e javavmwrapper jinput jutils libICE libSM libX11 libXau libXcursor libXdmcp libXext libXfixes libXi libXrandr libXrender libXt libXtst libXxf86vm libfontenc libinotify libmysofa libxcb lwjgl mkfontscale openal-soft openjdk8 png xorgproto xrandr